# Generated by Django 6.0.7 on 2026-08-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MondayIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_id", models.CharField(max_length=50, unique=True)),
                ("board_name", models.CharField(max_length=200)),
                ("access_token", models.TextField()),
                ("webhook_id", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FranchiseDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday_item_id", models.CharField(max_length=50, unique=True)),
                ("franchise_name", models.CharField(max_length=255)),
                ("market", models.CharField(blank=True, max_length=100)),
                ("stage", models.CharField(max_length=50)),
                ("loi_date", models.DateField(blank=True, null=True)),
                ("under_contract_date", models.DateField(blank=True, null=True)),
                ("under_development_date", models.DateField(blank=True, null=True)),
                ("open_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("hold_date", models.DateField(blank=True, null=True)),
                ("monday_created_at", models.DateTimeField(blank=True, null=True)),
                ("monday_updated_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franchises",
                        to="crm.mondayintegration",
                    ),
                ),
            ],
        ),
    ]
