# Generated by Django 6.0.7 on 2026-08-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="franchisedevelopment",
            name="integration",
        ),
    ]
